# Generated by Django 4.1 on 2022-09-28 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
